# **NUMPY**

In [ ]:
import numpy as np

x = np.array( [1,2,3,4,5] )
print(x)
print(type(x))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
y = [1,2,3,4,5]
print(y)
print(type(y))

[1, 2, 3, 4, 5]
<class 'list'>


In [ ]:
%timeit [ j**4 for j in range(1,9) ]

567 ns ± 9.81 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
%timeit np.arange(1,9)**4

2.01 µs ± 300 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# **NUMPY ARRAYS**

In [ ]:
import numpy as np
y = np.array( [ 1 ,2 ,3, 4, 5, 5] )
print(y)

print(y.ndim) # to find dimension of array

[1 2 3 4 5 5]
1


In [ ]:
l = []
for i in range(0,5):
  var = int(input("enter any number : "))
  l.append(var)
print(l)
print(np.array(l))

enter any number : 10
enter any number : 20
enter any number : 30
enter any number : 40
enter any number : 50
[10, 20, 30, 40, 50]
[10 20 30 40 50]


In [ ]:
# 2-D array
arr2 = np.array( [ [1,2,3] ,[4,5,6]] )
print(arr2)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
# 3-D array
arr3 = np.array( [ [ [1,2,3] ,[4,5,6] , [7,8,9] ]] )
print(arr3)
print(arr3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [ ]:
# n dimension array
arr4 = np.array( [ 1,2,3,4,5] , ndmin=10 )
print(arr4)
print(arr4.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10


ARRAY FUNCTIONS

In [ ]:
# creating array with all zeros
import numpy as np
arr_zeros = np.zeros( 4 )
print(arr_zeros)

print()

arr_zeros_1 = np.zeros( (4,3) )
print(arr_zeros_1)

print()

# creating array with all ones

arr_ones = np.ones( 4 )
print(arr_ones)

print()

arr_ones_1 = np.ones( (4,3) )
print(arr_ones_1)

[0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# creating an empty array
arr_emp = np.empty(4)
print(arr_emp)

print()

arr_emp1 = np.empty( (4,3) )
print(arr_emp1)


[1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#creating array with a range of elements
arr_rn = np.arange(10)
print(arr_rn)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# creating array with diagonal one's
arr_diagonal = np.eye(6)
print(arr_diagonal)

print()

arr_diagonal1 = np.eye(3)
print(arr_diagonal1)

print()

arr_diagonal3 = np.eye(3,4)
print(arr_diagonal3)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [ ]:
# creating arrray that are spaced linearly within specified intervals
arr_1 = np.linspace(0,20,num=5)
print(arr_1)

print()



[ 0.  5. 10. 15. 20.]



# **rand**

In [ ]:
import numpy as np
var = np.random.rand(5)
print(var)

print()

var1 = np.random.rand(2,3)
print(var1)

[0.18618896 0.94228303 0.56546512 0.32343242 0.31492241]

[[0.76973674 0.16514415 0.81594127]
 [0.38519047 0.46346676 0.75550978]]


# **randn**

In [ ]:
import numpy as np
var = np.random.randn(5)
print(var)

print()

var1 = np.random.randn(2,3)
print(var1)

[-0.02974128 -1.43404978  0.01757261  0.71147375  0.40031275]

[[-0.07634329  1.49727037 -0.32321391]
 [-0.06266243  0.22509856  0.05561051]]


# **ranf()**

In [ ]:
import numpy as np
var = np.random.ranf(5)
print(var)

print()

var1 = np.random.ranf( (2,3) )
print(var1)

[0.9743944  0.85304917 0.51569138 0.58272397 0.86490694]

[[0.50254406 0.27866665 0.46393102]
 [0.55990426 0.11363699 0.2914804 ]]


# **randint()**

In [ ]:
import numpy as np
var = np.random.randint(0,10,5)
print(var)

print()

var1 = np.random.randint( 0,20, (2,3) )
print(var1)

[3 6 9 0 6]

[[ 2 10 15]
 [ 9  7  0]]


# **DATA TYPES**

In [ ]:
import numpy as np
var = np.array( [1,2,3,4,5,6,7,8,9] )
print("data type : ",var.dtype)

print()

data type :  int64



In [ ]:
import numpy as np
var = np.array( [1.2,2.3,3.9,4.0,5.1,6.2,7.5,8.3,9.1] )
print("data type : ",var.dtype)

print()

data type :  float64



In [ ]:
import numpy as np
var = np.array( ["a" , "b" , "c" , "d"] )
print("data type : ",var.dtype)

print()

data type :  <U1



In [ ]:
import numpy as np
var = np.array( [1.2,2.3,"a" , "b" , "c" , "d"] )
print("data type : ",var.dtype)

print()

data type :  <U32



# **DATA CONVERSIONS**

In [ ]:
import numpy as np
var = np.array( [1,2,3,4,5,6,7,8,9] , dtype=np.int8 )
print("data type : ",var.dtype)
print(var)

print()

var1 = np.array( [1,2,3,4,5,6,7,8,9] , dtype='i' )
print("data type : ",var1.dtype)
print(var1)

data type :  int8
[1 2 3 4 5 6 7 8 9]

data type :  int32
[1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np
var = np.array( [1,2,3,4,5,6,7,8,9] , dtype='f' )
print("data type : ",var.dtype)
print(var)

data type :  float32
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
import numpy as np
var = np.array( [1,2,3,4,5] )
new_var_float = np.float32(var)
new_var_int = np.int_(new_var_float)

print(var)
print("data type : ",var.dtype)

print()
print(new_var_float)
print("data type : ",new_var_float.dtype)

print()
print(new_var_int)
print("data type : ",new_var_int.dtype)


[1 2 3 4 5]
data type :  int64

[1. 2. 3. 4. 5.]
data type :  float32

[1 2 3 4 5]
data type :  int64


In [ ]:
x3 = np.array( [1,2,3,4,5] )
new_1 = x3.astype(float)

print(x3)
print("data type : ",x3.dtype)
print(new_1)
print("data type : ",new_1.dtype)

[1 2 3 4 5]
data type :  int64
[1. 2. 3. 4. 5.]
data type :  float64


# **ARITHMETIC OPERATIONS ON ARRAY**

1D array

In [ ]:
import numpy as np
var = np.array( [1,2,3,4,5])
var_add = var+3
var_Add = np.add(var,3)
print(var)
print(var_add)

[1 2 3 4 5]
[4 5 6 7 8]


In [ ]:
import numpy as np
var = np.array( [1,2,3,4,5])
var_subt= var-3
print(var)
print(var_subt)

[1 2 3 4 5]
[-2 -1  0  1  2]


In [ ]:
import numpy as np
var = np.array( [1,2,3,4,5])
var_prod = var*3
print(var)
print(var_prod)

[1 2 3 4 5]
[ 3  6  9 12 15]


In [ ]:
import numpy as np
var = np.array( [1,2,3,4,5])
var_div = var/2
print(var)
print(var_div)

[1 2 3 4 5]
[0.5 1.  1.5 2.  2.5]


2D array

In [ ]:
import numpy as np
var1 = ( [[1,2,3],[4,5,6]] )
var2= ( [[1,2,3],[4,5,6]] )
print(var1)
print(var2)
var_add = var1+var2
print(var_add)

[[1, 2, 3], [4, 5, 6]]
[[1, 2, 3], [4, 5, 6]]
[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]


In [ ]:
import numpy as np
var = ( [1,2,3,4] )
var_new = np.reciprocal(var)
print(var_new)

print()

var2 = ( [10,20,30,40] )
var_new = np.reciprocal(var2)
print(var_new)

print()

var3 = np.array( [10,20,30,40] ,dtype=float)
var_new = np.reciprocal(var3)
print(var_new)

[1 0 0 0]

[0 0 0 0]

[0.1        0.05       0.03333333 0.025     ]


In [ ]:
# finding the minimum and maximum element in an array
import numpy as np
var = np.array( [15,3,29,60,100,46,34] )
print("min elem : ",np.min(var))  # find min elem of array
print("maxm elem : ",np.max(var)) # find maximum elem of array

print("min elem index : ",)
print("max elem index : ",np.argmax(var)) # find index of max elem of array
print("min elem index : ",np.argmin(var)) # find index of min elem of array

min elem :  3
maxm elem :  100
min elem index : 
max elem index :  4
min elem index :  1


In [ ]:
# finding the minimum and maximum element in an 2-D array
var = np.array( [[5,2,6],[8,9,3]] )
print("min row wise : ",np.min(var,axis=1 ) )  # colm-wise minimum
print("min colm wise : ",np.min(var,axis=0) )  # row-wise minimum

min row wise :  [2 3]
min colm wise :  [5 2 3]


In [ ]:
var = np.array( [2,4,9,16,25])
print(var)
print("sqrt : ",np.sqrt(var))

[ 2  4  9 16 25]
sqrt :  [1.41421356 2.         3.         4.         5.        ]


In [ ]:
# finding sin and cos value ans cumsum
var = np.array( [1,3,5,7,9])
print(var)
print("sin : ",np.sin(var))
print("cos : ",np.cos(var))
print("cumsum : ",np.cumsum(var))

[1 3 5 7 9]
sin :  [ 0.84147098  0.14112001 -0.95892427  0.6569866   0.41211849]
cos :  [ 0.54030231 -0.9899925   0.28366219  0.75390225 -0.91113026]
cumsum :  [ 1  4  9 16 25]


# SHAPE

In [ ]:
import numpy as np
var = np.array( [1,2,3,4,5] )
print(var)
print("shape :" ,var.shape)

print()
var2 = np.array( [ [5,6,7,8],[9,1,2,3] ] )
print(var2)
print("shape : ",var2.shape)

print()
var3 = np.array( [1,2,3,4],ndmin=5)
print(var3)
print("shape : ", var3.shape)

[1 2 3 4 5]
shaep : (5,)

[[5 6 7 8]
 [9 1 2 3]]
shape :  (2, 4)

[[[[[1 2 3 4]
    [1 2 3 4]]]]]
shape :  (1, 1, 1, 2, 4)


# **reshape**

In [ ]:
import numpy as np
var = np.array( [1,2,3,4,5,6,7,8,9] )
print(var)
print("dim : ",var.ndim)
print()

x = var.reshape(3,3)
print(x)
print("dim : ",x.ndim)

[1 2 3 4 5 6 7 8 9]
dim :  1

[[1 2 3]
 [4 5 6]
 [7 8 9]]
dim :  2


In [ ]:
import numpy as np
var = np.array( [1,2,3,4,5,6,7,8,9,1,2,3] )
print(var)
print("dim : ",var.ndim)
print()

x = var.reshape(2,3,2)
print(x)
print("dim : ",x.ndim)

print()
new = x.reshape(-1)
print(new)
print("dim : ",new.ndim)

[1 2 3 4 5 6 7 8 9 1 2 3]
dim :  1

[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [9 1]
  [2 3]]]
dim :  3

[1 2 3 4 5 6 7 8 9 1 2 3]
dim :  1


# **BROADCASTING**

In [ ]:
import numpy as np
var1 = np.array( [1,2,3,4,5] )
var2 = np.array( [1,2,3,4,5] )
print("var1 : ",var1 , " shape : ",var1.shape)
print()
print("Var2 : ",var2 , " shape : ",var2.shape)
print()
print("var1 + var2 : ",var1+var2 , " shape : ",(var1+var2).shape)

var1 :  [1 2 3 4 5]  shape :  (5,)

Var2 :  [1 2 3 4 5]  shape :  (5,)

var1 + var2 :  [ 2  4  6  8 10]  shape :  (5,)


In [ ]:
# can be broadcasted if either one of them is '1' or have the 'same' value while going from right to left
var1 = np.array( [1,2,3,4,5] )
var2 = np.array( [ [1],[2],[3],[4],[5] ] )
print("var1 : ")
print(var1 , " shape : ",var1.shape)

print()
print("Var2 : ")
print(var2 , " shape : ",var2.shape)

print()
print("var1 + var2 : ")
print(var1+var2 , " shape : ",(var1+var2).shape)

var1 : 
[1 2 3 4 5]  shape :  (5,)

Var2 : 
[[1]
 [2]
 [3]
 [4]
 [5]]  shape :  (5, 1)

var1 + var2 : 
[[ 2  3  4  5  6]
 [ 3  4  5  6  7]
 [ 4  5  6  7  8]
 [ 5  6  7  8  9]
 [ 6  7  8  9 10]]  shape :  (5, 5)


In [ ]:
# add of array of (2 X 1) + (2 X 3)
var1 = np.array([ [1],[2] ] )
var2 = np.array( [ [1,2,3],[4,5,6] ] )
print("var1 : ")
print(var1 , " shape : ",var1.shape)

print()
print("Var2 : ")
print(var2 , " shape : ",var2.shape)

print()
print("var1 + var2 : ")
print(var1+var2 , " shape : ",(var1+var2).shape)

var1 : 
[[1]
 [2]]  shape :  (2, 1)

Var2 : 
[[1 2 3]
 [4 5 6]]  shape :  (2, 3)

var1 + var2 : 
[[2 3 4]
 [6 7 8]]  shape :  (2, 3)


# **INDEXING**

In [ ]:
import numpy as np
# 1D array
x = np.array( [1 , 2 , 3 , 4] )
#              0   1   2   3
#             -4  -3  -2  -1
print("array : ",x)
print("x[2] : ",x[2])
print("x[-4] : ",x[-4] )


array :  [1 2 3 4]
x[2] :  3
x[-4] :  1


In [ ]:
# 2D array
x = np.array( [ [1,2,3,4] , [5,6,7,8] , [9,4,5,6] ] )
print(x)
print()

print("dim : ",x.ndim)
print()

print("x[0][3] : ",x[0][3])
print()

print("x[2][2] : ",x[2][2])

[[1 2 3 4]
 [5 6 7 8]
 [9 4 5 6]]

dim :  2

x[0][3] :  4

x[2][2] :  5


In [ ]:
# 3D array
x = np.array ( [ [ [1,2,3,4] , [5,6,7,8] ] ,[ [9,4,5,6] , [2,4,5,8] ] ] )
print(x)
print()

print("dim : ",x.ndim)
print()

print("x[0][1][3] : ",x[0][1][3])
print()

print("x[1][1][2] : ",x[1][1][2])

[[[1 2 3 4]
  [5 6 7 8]]

 [[9 4 5 6]
  [2 4 5 8]]]

dim :  3

x[0][1][3] :  8

x[1][1][2] :  5


# **SLICING**

In [ ]:
import numpy as np
# 1D array
x = np.array( [1 , 2 , 3 , 4 , 5 , 6 , 7 ] )
#              0   1   2   3   4   5   6
#             -7  -6  -5  -4  -3  -2  -1
print("array : ",x)
print()

print("3 to 7 : ",x[2:7])
print()

print("strt to 5 : ",x[:5] )
print()

print("3 to end : ",x[2:] )
print()

print("step -> 2 : ",x[::2])
print()

array :  [1 2 3 4 5 6 7]

3 to 7 :  [3 4 5 6 7]

strt to 5 :  [1 2 3 4 5]

3 to end :  [3 4 5 6 7]

step -> 2 :  [1 3 5 7]



In [ ]:
# for 2D array
x = np.array( [ [1,2,3,4] , [5,6,7,8] , [10,11,12,13] ] )
print(x)
print()

print("6 to 8 : ",x[1,1:])
print()

print("10 to 12 : ",x[2,2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]

6 to 8 :  [6 7 8]

10 to 12 :  [12 13]


# **ITERATING IN AN ARRAY**

In [ ]:
import numpy as np

# for 1D array
var = ( [1,2,3,4,5,6,7,8,] )
print(var)

print()

for i in var:
  print(i)

[1, 2, 3, 4, 5, 6, 7, 8]

1
2
3
4
5
6
7
8


In [ ]:
# for 2D array
var = ( [ [1,2,3,4] , [5,6,7,8,] ] )
print(var)

print()

for i in var:
  for j in i:
    print(j)

[[1, 2, 3, 4], [5, 6, 7, 8]]

1
2
3
4
5
6
7
8


In [ ]:
# for 3D array
var = ( [ [ [1,2,3,4] , [5,6,7,8,] ] ] )
print(var)

print()

for i in var:
  for j in i:
    for k in j:
      print(k)

[[[1, 2, 3, 4], [5, 6, 7, 8]]]

1
2
3
4
5
6
7
8


# NDITER() funcion

In [ ]:
var = ( [ [ [1,2,3,4] , [5,6,7,8,] ] ] )
print(var)

print()

for i in np.nditer(var):
  print(i)

[[[1, 2, 3, 4], [5, 6, 7, 8]]]

1
2
3
4
5
6
7
8


In [ ]:
# iterating over the data and also converting its data type
var = ( [ [ [1,2,3,4] , [5,6,7,8,] ] ] )
print(var)

print()

for i in np.nditer(var , flags=['buffered'] , op_dtypes=["S"] ): # convert the data to string
  print(i)

[[[1, 2, 3, 4], [5, 6, 7, 8]]]

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'7')
np.bytes_(b'8')


## iterating array with index values


In [ ]:
var = ( [ [ [1,2,3,4] , [5,6,7,8] ] , [ [-1,-2,-3,-4] , [-5,-6,-7,-8] ] ] )
print(var)

print()

for i in np.ndenumerate(var):
  print(i)

[[[1, 2, 3, 4], [5, 6, 7, 8]], [[-1, -2, -3, -4], [-5, -6, -7, -8]]]

((0, 0, 0), np.int64(1))
((0, 0, 1), np.int64(2))
((0, 0, 2), np.int64(3))
((0, 0, 3), np.int64(4))
((0, 1, 0), np.int64(5))
((0, 1, 1), np.int64(6))
((0, 1, 2), np.int64(7))
((0, 1, 3), np.int64(8))
((1, 0, 0), np.int64(-1))
((1, 0, 1), np.int64(-2))
((1, 0, 2), np.int64(-3))
((1, 0, 3), np.int64(-4))
((1, 1, 0), np.int64(-5))
((1, 1, 1), np.int64(-6))
((1, 1, 2), np.int64(-7))
((1, 1, 3), np.int64(-8))


# **COPY VS VIEW**

In [ ]:
import numpy as np
var = np.array( [1,2,3,4,5] )
cpy = var.copy()

print("Var : ",var)
print()
print("copy : ",cpy)

var[2]=30

# when actual variable changes copy don't change
print()
print("Var : ",var)
print()
print("copy : ",cpy)

Var :  [1 2 3 4 5]

copy :  [1 2 3 4 5]

Var :  [ 1  2 30  4  5]

copy :  [1 2 3 4 5]


In [ ]:
var1 = np.array( [5,6,7,8,9] )
viw = var1.view()

print("var1 : ",var1)
print()
print("view : ",viw)

var1[3]=100

# when original variable changes view changes too
print()
print("var1 : ",var1)
print()
print("view : ",viw)

var1 :  [5 6 7 8 9]

view :  [5 6 7 8 9]

var1 :  [  5   6   7 100   9]

view :  [  5   6   7 100   9]


# **joining and split**

# join

In [ ]:
# joining 1-D arrays
arr1 = np.array( [1,2,3,4,5] )
arr2 = np.array( [ 5,6,7,8,9] )

print("Arr1 : ",arr1)
print()
print("Arr2 : ",arr2)
print()

arr3 = np.concatenate( (arr1,arr2) )
print("joined arr : ",arr3)

Arr1 :  [1 2 3 4 5]

Arr2 :  [5 6 7 8 9]

joined arr :  [1 2 3 4 5 5 6 7 8 9]


In [ ]:
# joining 2-D arrays
arr1 = np.array( [ [1,2] , [3,4,]  ] )
arr2 = np.array( [ [5,6] , [7,8,]  ] )

print("Arr1 : \n",arr1)
print()
print("Arr2 : \n",arr2)
print()

arr3 = np.concatenate( (arr1,arr2) ,axis=1) # towards coloumns
arr4 = np.concatenate( (arr1,arr2) , axis=0) # towards rows
print("joined arr (Axis =1 )  : \n",arr3)
print()
print("joined arr (Axis = 0)  : \n",arr4)

Arr1 : 
 [[1 2]
 [3 4]]

Arr2 : 
 [[5 6]
 [7 8]]

joined arr (Axis =1 )  : 
 [[1 2 5 6]
 [3 4 7 8]]

joined arr (Axis = 0)  : 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# stack function
arr1 = np.array( [1,2,3,4] )
arr2 = np.array( [5,6,7,8] )

print("Arr1 : \n",arr1)
print()
print("Arr2 : \n",arr2)
print()

arr3 = np.stack( (arr1,arr2) ,axis=1)
arr4 = np.stack( (arr1,arr2) , axis=0)
print("joined arr (Axis =1 )  : \n",arr3)
print()
print("joined arr (Axis = 0)  : \n",arr4)

Arr1 : 
 [1 2 3 4]

Arr2 : 
 [5 6 7 8]

joined arr (Axis =1 )  : 
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]

joined arr (Axis = 0)  : 
 [[1 2 3 4]
 [5 6 7 8]]


# types of stack fucntion

In [ ]:
arr1 = np.array( [1,2,3,4] )
arr2 = np.array( [5,6,7,8] )

print("Arr1 : \n",arr1)
print()
print("Arr2 : \n",arr2)
print()

arr3 = np.hstack( (arr1,arr2) )  # along rows
arr4 = np.vstack( (arr1,arr2) )  # along coloumns
arr5 = np.dstack( (arr1,arr2) )  # along heights

print("joined arr (hstack) : \n",arr3)
print()

print("joined arr (vstack) : \n",arr4)
print()

print("joined arr (dstack) : \n",arr5)
print()

Arr1 : 
 [1 2 3 4]

Arr2 : 
 [5 6 7 8]

joined arr (hstack) : 
 [1 2 3 4 5 6 7 8]

joined arr (vstack) : 
 [[1 2 3 4]
 [5 6 7 8]]

joined arr (dstack) : 
 [[[1 5]
  [2 6]
  [3 7]
  [4 8]]]



# SPLIT

In [ ]:
arr1 = np.array( [1,2,3,4,5,6] )

print("Arr1 : ",arr1)
print()

arr2 = np.array_split(arr1,3)
print("split into 3 : ",arr2)
print()

arr3 = np.array_split(arr1,4)
print("split into 4 : ",arr3)

Arr1 :  [1 2 3 4 5 6]

split into 3 :  [array([1, 2]), array([3, 4]), array([5, 6])]

split into 4 :  [array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
import numpy as np
arr1 = np.array( [ 1 , 2 , 3 , 4 , 5 , 6 ] )

print("Arr1 : ",arr1)
print()

arr2 = np.array_split(arr1,3)
print("Arr2 -> split into 3 : ",arr2)
print()

arr3 = np.array_split(arr1,4)
print("Arr3 -> split into 4 : ",arr3)

print()
print("arr3[3] : ",arr3[3])

Arr1 :  [1 2 3 4 5 6]

Arr2 -> split into 3 :  [array([1, 2]), array([3, 4]), array([5, 6])]

Arr3 -> split into 4 :  [array([1, 2]), array([3, 4]), array([5]), array([6])]

arr3[3] :  [6]


In [ ]:
var1 = np.array( [ [1,2,3] , [4,5,6] ] )
var2 = np.array_split(var1 , 2 )

print("var1 : \n",var1)
print()

print("var2 : \n",var2)
print()

var3 = np.array_split(var1 , 3 , axis=1 )   # column-wise
print("var3 : \n",var3)
print()

var4 = np.array_split(var1 , 3 , axis=0 )   # row - wise
print("var4 : \n",var4)
print()


var1 : 
 [[1 2 3]
 [4 5 6]]

var2 : 
 [array([[1, 2, 3]]), array([[4, 5, 6]])]

var3 : 
 [array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]

var4 : 
 [array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64)]



# **SEARCH**

In [ ]:
import numpy as np
var = np.array( [1 , 2 , 3 , 4 , 7 , 8 , 1 , 3 , 0 , 2 , 3 , 6 , 8 , 1 ,  8] )
# index ->       0 , 1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 10, 11, 12, 13, 14

find1 = np.where( var == 8 )

print("character 8 at indexes -> ",find1)
print()

find2 = np.where( (var % 2) == 0 )

print(" (var % 2) == 0 -> ",find2)
print()

find3 = np.where( (var +1) == 9)
print("(Var + 1) == 5 -> ",find3)

character 8 at indexes ->  (array([ 5, 12, 14]),)

 (var % 2) == 0 ->  (array([ 1,  3,  5,  8,  9, 11, 12, 14]),)

(Var + 1) == 5 ->  (array([ 5, 12, 14]),)


In [ ]:
# search sorted array -> will search for a particular index where a value can be placed in a sorted array

var = np.array( [1 , 2 , 5 , 7 , 9 , 11 , 13 , 15 , 19] )
# index ->       0   1   2   3   4   5     6    7    8

find1 = np.searchsorted(var , 6)
print("number 6 placed at index : ",find1)
print()

find2 = np.searchsorted(var,4)
print("number 4 placed at index : ",find2)
print()

find3 = np.searchsorted(var,9)
print("number 9 placed at index : ",find3)
print()

find4 = np.searchsorted(var , 11 , side="right") # "right" insert after existing values
print("number 11 placed at index : ",find4)
print()

find5 = np.searchsorted(var , 11 , side="left") # "left" insert before existing values
print("number 11 placed at index : ",find5)
print()

find6 = np.searchsorted(var,[3,6,10])
print("numbers [3,6,10] placed at index : ",find6)
print()


number 6 placed at index :  3

number 4 placed at index :  2

number 9 placed at index :  4

number 11 placed at index :  6

number 11 placed at index :  5

numbers [3,6,10] placed at index :  [2 3 5]

[ 1  2  5  7  9 11 13 15 19]


# **SORT**

In [ ]:
import numpy as np

# 1D array
var1 = np.array( [ 10 , 100 , 34 , 4 , 89 , 99 , 20 ] )
print("array : ",var1)
print()

var1 = np.sort(var1)

print("sorted array : ",var1)
print()


var2 = np.array( ["g" , "l" , "t" , "a" , "z" ,"h"] )
print("array : ",var2)
print()

var2 = np.sort(var2)

print("sorted array : ",var2)
print()

array :  [ 10 100  34   4  89  99  20]

sorted array :  [  4  10  20  34  89  99 100]

array :  ['g' 'l' 't' 'a' 'z' 'h']

sorted array :  ['a' 'g' 'h' 'l' 't' 'z']



In [ ]:
#2D array
var = np.array( [ [ 10 , 100 , 34 ] , [ 4 , 89 , 9] , [ 20 , 10 , 9 ] ] )
print("array : \n",var)
print()

var = np.sort(var)

print("sorted array : \n",var)
print()


array : 
 [[ 10 100  34]
 [  4  89   9]
 [ 20  10   9]]

sorted array : 
 [[ 10  34 100]
 [  4   9  89]
 [  9  10  20]]



# **Filter Array**



In [ ]:
var = np.array( [1,2,3,4,5])
fil = [True , False , True , True , False]
new_var = var[fil]

print("original array : ",var)
print()
print("filtered array : ", new_var)

print()
print("type(new_var) : ",type(new_var))

original array :  [1 2 3 4 5]

filtered array :  [1 3 4]

type(new_var) :  <class 'numpy.ndarray'>


# **SHUFFLE**

In [ ]:
import numpy as np
var = np.array( [1,2,3,4,5,6,7,8,9,10] )

np.random.shuffle(var)
print(var)

[ 2  8 10  6  3  4  9  5  7  1]


# **UNIQUE**

In [ ]:
arr = np.array( [1,2,4,1,9,5,3,6,7,10,2,3,4,2,3] )
print("original array : ",arr)
print()

new_arr = np.unique(arr)
print(new_arr)
print()

# to get addresses of unique elements also
new_arr1 = np.unique(arr , return_index=True)
print(new_arr1)
print()

# return count also
new_arr2 = np.unique(arr , return_index=True , return_counts=True)
print(new_arr2)
print()

[ 1  2  3  4  5  6  7  9 10]

(array([ 1,  2,  3,  4,  5,  6,  7,  9, 10]), array([0, 1, 6, 2, 5, 7, 8, 4, 9]))

(array([ 1,  2,  3,  4,  5,  6,  7,  9, 10]), array([0, 1, 6, 2, 5, 7, 8, 4, 9]), array([2, 3, 3, 2, 1, 1, 1, 1, 1]))



# **resize**

In [ ]:
var = np.array( [1,2,3,4,5,6] )
new_var = np.resize(var,(2,3))

print("original array : ",var)
print()

print("resized to (2,3) : \n",new_var)
print()


original array :  [1 2 3 4 5 6]

resized to (2,3) : 
 [[1 2 3]
 [4 5 6]]



# **flatten**

In [ ]:
var = np.array( [1,2,3,4,5,6] )
new_var = np.resize(var,(2,3))

print("original array : ",var)
print()

print("resized to (2,3) : \n",new_var)
print()

print("flattened array : \n",new_var.flatten())
print()

print("flattened array : \n",new_var.flatten(order = "F"))  # orders can be as -> 'A' , 'C' , 'F' , 'K
print()

print("flattened array : \n",new_var.flatten(order = "C"))
print()

original array :  [1 2 3 4 5 6]

resized to (2,3) : 
 [[1 2 3]
 [4 5 6]]

flattened array : 
 [1 2 3 4 5 6]

flattened array : 
 [1 4 2 5 3 6]

flattened array : 
 [1 2 3 4 5 6]



# **ravel**

In [ ]:
var = np.array( [1,2,3,4,5,6] )
new_var = np.resize(var,(2,3))

print("original array : ",var)
print()

print("resized to (2,3) : \n",new_var)
print()

print("flattened array : \n",new_var.flatten())
print()

print("ravel : \n",new_var.ravel())
print()

print("ravel : \n",new_var.ravel(order = 'C'))
print()

original array :  [1 2 3 4 5 6]

resized to (2,3) : 
 [[1 2 3]
 [4 5 6]]

flattened array : 
 [1 2 3 4 5 6]

ravel : 
 [1 2 3 4 5 6]

ravel : 
 [1 2 3 4 5 6]



# **INSERT**

In [ ]:
# insert(arr_name , position , value) -> it inserts only integer values
import numpy as np

arr = np.array( [10,20,30,40,50] )
print("arr : ",arr)
print()

new = np.insert(arr , 1 , 1)
print("after insertion : ",new)
print()

new = np.insert(arr , (1,3,5) , 100)
print("after insertion : ",new)
print()

new = np.insert(arr , 1 , 5.5)
print("after insertion : ",new)
print()

arr :  [10 20 30 40 50]

after insertion :  [10  1 20 30 40 50]

after insertion :  [ 10 100  20  30 100  40  50 100]

after insertion :  [10  5 20 30 40 50]



In [ ]:
import numpy as np

arr = np.array( [ [10,20,30 ] , [40,50,60] ] )
print("arr : \n",arr)
print()

new = np.insert(arr , 1 , 1 , axis=0)
print("after insertion : \n",new)
print()

new = np.insert(arr , 2 , [1,3,5] , axis=0)
print("after insertion : \n",new)
print()

new = np.insert(arr , 2 ,3 , axis=1)
print("after insertion : \n",new)
print()

arr : 
 [[10 20 30]
 [40 50 60]]

after insertion : 
 [[10 20 30]
 [ 1  1  1]
 [40 50 60]]

after insertion : 
 [[10 20 30]
 [40 50 60]
 [ 1  3  5]]

after insertion : 
 [[10 20  3 30]
 [40 50  3 60]]



# **append**

In [ ]:
arr = np.array( [10,20,30,40,50] )
print("arr : ",arr)
print()

new = np.append(arr , 1)
print("after insertion : ",new)
print()

new = np.append(arr , [1,2,3])
print("after insertion : ",new)
print()

new = np.append(arr , 7.5)
print("after insertion : ",new)
print()

arr :  [10 20 30 40 50]

after insertion :  [10 20 30 40 50  1]

after insertion :  [10 20 30 40 50  1  2  3]

after insertion :  [10.  20.  30.  40.  50.   7.5]



In [ ]:
import numpy as np

arr = np.array([[10,20,30],
                [40,50,60]])

print("arr : \n", arr)
print()

# append row
new = np.append(arr, [[1,2,3]], axis=0)

print("after row insertion : \n", new)
print()

# append column
new = np.append(arr, [[11],[12]], axis=1)

print("after column insertion : \n", new)
print()

arr : 
 [[10 20 30]
 [40 50 60]]

after row insertion : 
 [[10 20 30]
 [40 50 60]
 [ 1  2  3]]

after column insertion : 
 [[10 20 30 11]
 [40 50 60 12]]



# **delete**

In [ ]:
arr = np.array( [10,20,30,40,50] )
print("arr : ",arr)
print()

new = np.delete(arr , 1)
print("after deletion : ",new)
print()

new = np.delete(arr , [1,2,3])
print("after deletion : ",new)
print()

arr :  [10 20 30 40 50]

after deletion :  [10 30 40 50]

after deletion :  [10 50]



# **matrix**

In [ ]:
mat = np.matrix([[10,20,30],
                [40,50,60]])

print("matrix : \n", mat)
print()
print("type : ",type(mat))

matrix : 
 [[10 20 30]
 [40 50 60]]

type :  <class 'numpy.matrix'>


In [ ]:
mat1 = np.matrix( [ [1,2],[4,5] ] )
mat2 = np.matrix( [ [4,5],[1,2] ] )

print("mat1 : \n",mat1)
print()
print("mat2 : \n",mat2)

print()
print("mat1 + mat2 : \n",mat1 + mat2)

print()
print("mat1 - mat2 : \n",mat1 - mat2)

print()
print("mat1 * mat2 : \n",mat1 * mat2)

print()
print("mat1 . dot (mat2) : \n",mat1.dot(mat2))

print()
print("mat1 / mat2 : \n",mat1 / mat2)

mat1 : 
 [[1 2]
 [4 5]]

mat2 : 
 [[4 5]
 [1 2]]

mat1 + mat2 : 
 [[5 7]
 [5 7]]

mat1 - mat2 : 
 [[-3 -3]
 [ 3  3]]

mat1 * mat2 : 
 [[ 6  9]
 [21 30]]

mat1 . dot (mat2) : 
 [[ 6  9]
 [21 30]]

mat1 / mat2 : 
 [[0.25 0.4 ]
 [4.   2.5 ]]


In [ ]:
# matrix multiplication different from arrays
arr1 = np.array( [ [1,2,3],[4,5,6] ] )
arr2 = np.array( [ [4,5,6],[1,2,3] ] )

print("Arr1 : \n",arr1)
print()
print("Arr2 : \n",arr2)

print()
print("arr1 * arr2 : \n",arr1 * arr2)

Arr1 : 
 [[1 2 3]
 [4 5 6]]

Arr2 : 
 [[4 5 6]
 [1 2 3]]

arr1 * arr2 : 
 [[ 4 10 18]
 [ 4 10 18]]


In [ ]:
# TRANSPOSE
mat = np.matrix( [ [10,20,30,40] , [50,60,70,80] ] )

print("matrix : \n",mat)
print()

print("transpose : \n",np.transpose(mat))
print()

print("transpose : \n",mat.T)
print()

# SWAPAXES
mat1 = np.matrix( [ [10,20,30,40] , [50,60,70,80] ] )
print("matrix : \n",mat1)
print()

print("swapaxes : \n",np.swapaxes(mat,0,1) )
print()

# in transpose you can control which axes cnvts to which another axis
# in swapaxes it changes only 2 axes

matrix : 
 [[10 20 30 40]
 [50 60 70 80]]

transpose : 
 [[10 50]
 [20 60]
 [30 70]
 [40 80]]

transpose : 
 [[10 50]
 [20 60]
 [30 70]
 [40 80]]

matrix : 
 [[10 20 30 40]
 [50 60 70 80]]

swapaxes : 
 [[10 50]
 [20 60]
 [30 70]
 [40 80]]



# INVERSE

In [ ]:
import numpy as np
var = np.matrix( [ [1,2,3],[0,1,4],[5,6,0] ] )
print("matrix : \n",var)
print()
print("inverse : \n",np.linalg.inv(var))

matrix : 
 [[1 2 3]
 [0 1 4]
 [5 6 0]]

inverse : 
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [ ]:
# power function -> power(var , n)
# if n = 0 --> gives identity matrix
# if n < 0 --> gives (inverse)^power
# if n > 0 --> gives power
var = np.matrix( [ [1,2],[3,4] ] )
print("matrix : \n",var)
print()

print("power = 0 : \n",np.linalg.matrix_power(var ,0))
print()

print("power < 0 : \n",np.linalg.matrix_power(var ,-1))
print()

print("power > 0 : \n",np.linalg.matrix_power(var ,2))
print()

matrix : 
 [[1 2]
 [3 4]]

power = 0 : 
 [[1 0]
 [0 1]]

power < 0 : 
 [[-2.   1. ]
 [ 1.5 -0.5]]

power > 0 : 
 [[ 7 10]
 [15 22]]



In [ ]:
# determinant
var = np.matrix( [ [1,2],[3,4] ] )
print("matrix : \n",var)
print()

print("determinant : \n",np.linalg.det(var))


matrix : 
 [[1 2]
 [3 4]]

determinant : 
 -2.0000000000000004
